uartd: first implementation
zenitheesc/uartd pull request #1
Opened 2022-07-13 07:43 UTC by Grillo-0

The first implementation of a working daemon to communicate via UART on
the FrameWorkd environment.

2022-07-13 22:24 UTC, mairacanal requested changes
Antes de eu revisar, só para ver se eu entendo: você quer fazer o UART funcionar com CAN ID assim como CAN?

2022-07-13 22:24 UTC, mairacanal commented on CMakeLists.txt
> +  Uartd
Não deveria está entre aspas?

2022-07-13 22:24 UTC, mairacanal commented on CMakeLists.txt
> +#     dependency1 ...
Apagar

2022-07-22 13:51 UTC, Grillo-0 commented on CMakeLists.txt
> +  Uartd
Não

2022-07-22 16:50 UTC, Grillo-0 commented
> Antes de eu revisar, só para ver se eu entendo: você quer fazer o UART funcionar com CAN ID assim como CAN?

basicamente isso, como o código fo cand ja tava basicamente pronto eu usei muita coisa dele

2022-07-27 17:07 UTC, Math-42 requested changes

2022-07-27 17:07 UTC, Math-42 commented on config-files/zfkd.dbus.uartd.conf
> +    <allow own="zfkd.dbus.uartd"/>
mudar para default

2022-07-27 17:07 UTC, Math-42 commented on src/uartd.cpp
> +
Esses couts aqui vão ficar mesmo?

2022-07-29 13:49 UTC, Grillo-0 commented on src/uartd.cpp
> +
vão mas eu vou dar uma melhorada neles

2022-07-29 17:12 UTC, mairacanal commented on src/uartd.cpp
> +            // TODO(grillo): Enable calling a Method with zeros arguments
E esse TODO aqui?

2022-07-29 17:13 UTC, mairacanal commented
Acho mais apropriado que o @Math-42 veja esse PR do que eu, já que eu não sei qual o comportamento desejado.

2022-07-29 18:20 UTC, Math-42 commented
Tem um TODO ali no meio tbm, não sei se ele deveria ir mesmo @Grillo-0, e os cout, vão ficar assim mesmo?

2022-07-29 21:28 UTC, Grillo-0 commented
> Tem um TODO ali no meio tbm, não sei se ele deveria ir mesmo @Grillo-0, e os cout, vão ficar assim mesmo?

Verdade, tirei aqui, esse TODO é um problema do Frameworkd na verdade, cenas dos próximos PR's...

2022-07-29 21:29 UTC, Grillo-0 commented
> Tem um TODO ali no meio tbm, não sei se ele deveria ir mesmo @Grillo-0, e os cout, vão ficar assim mesmo?

No caso dos couts vão ficar assim mesmo, vai servir como log do uartd

2022-07-29 21:34 UTC, Math-42 approved these changes

2022-07-29 21:44 UTC, merged